#********************************************************************
#        Copyright (c) 2016, Lee Patterson
#        http://8BitCoder.com
#
#        created  :    05/18/2016 03:09:15 AM
#        filename :    Makefile
#        author   :    Lee Patterson (lee@8BitCoder.com)
#        
#        purpose  :    Make file for Linux operating system.
#*********************************************************************

lwasm --obj -9 -o ball.o ball.asm
lwlink -b -o ball.bin ball.o palette.o