*******************************************************************************
* 
* COPYRIGHT (C) 2018, LEE PATTERSON
* HTTP://8BITCODER.COM
*
* THIS IS FREE SOFTWARE: YOU CAN REDISTRIBUTE IT AND/OR MODIFY
* IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
* THE FREE SOFTWARE FOUNDATION, EITHER VERSION 3 OF THE LICENSE, OR
* (AT YOUR OPTION) ANY LATER VERSION.
* 
* THIS SOFTWARE IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
* BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
* MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
* GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
*
*******************************************************************************

            	ORG	$0E00

START		NOP				;FOR ZBUG

*STORE COORDS IN ROBOT ARRAY
		LDB	ROBIDX		;CURRENT ROBOT INDEX
		LDX	#ROBOTX			;ROBOTX ARRAY
		LDA	XPOS			;ROBOT'S XPOS
		STA	B,X			;STORE IN ARRAY
		LDX	#ROBOTY			;ROBOTY ARRAY
		LDA	YPOS			;ROBOT'S YPOS
		STA	B,X			;STORE IN ARRAY

		SWI
		
		
XPOS		FCB	8
YPOS		FCB	9

ROBMAX		EQU	4
ROBIDX		FCB	1
ROBOTX		fcb	$12,$34,$56,$78
ROBOTY		fcb	1,2,3,4


		END	START
